#!/usr/bin/env node
/**
 * Reads src/data/photos.ts manifest, transforms each source photo from
 * ../photos-from-rachel/ into AVIF + WebP + JPG variants at multiple
 * widths, and writes a generated TS module with LQIP base64 placeholders.
 *
 *   public/img/{id}-{w}.{avif,webp,jpg}
 *   src/data/photos.generated.ts
 *
 * Idempotent: skips variants that already exist and whose source mtime
 * is older than the variant. Pass FORCE=1 to rebuild all.
 */

import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');
const SOURCE_DIR = resolve(REPO_ROOT, '..', 'photos-from-rachel');
const OUT_DIR = resolve(REPO_ROOT, 'public', 'img');
const GENERATED_PATH = resolve(REPO_ROOT, 'src', 'data', 'photos.generated.ts');

const WIDTHS = [480, 768, 1280, 1920, 2560];
const FORMATS = /** @type {const} */ (['avif', 'webp', 'jpg']);
const QUALITY = { avif: 60, webp: 75, jpg: 82 };

const FORCE = process.env.FORCE === '1';

async function loadManifest() {
  const src = await readFile(resolve(REPO_ROOT, 'src', 'data', 'photos.ts'), 'utf8');
  // Extract the photos object literal between `export const photos = {` and `} as const`.
  const start = src.indexOf('export const photos = {');
  const end = src.indexOf('} as const satisfies', start);
  if (start === -1 || end === -1) throw new Error('Could not parse photos.ts');
  const body = src.slice(start + 'export const photos = '.length, end + 1);

  // Tiny TS-aware parser: pull out each `'id': { source: '...', ... }` entry.
  const entries = [];
  const re = /'([^']+)':\s*{\s*source:\s*'([^']+)'/g;
  let m;
  while ((m = re.exec(body))) {
    entries.push({ id: m[1], source: m[2] });
  }
  if (entries.length === 0) throw new Error('No photo entries parsed from manifest');
  return entries;
}

async function needsRebuild(sourcePath, outPath) {
  if (FORCE) return true;
  if (!existsSync(outPath)) return true;
  const [s, o] = await Promise.all([stat(sourcePath), stat(outPath)]);
  return s.mtimeMs > o.mtimeMs;
}

async function processOne(entry) {
  const sourcePath = join(SOURCE_DIR, entry.source);
  if (!existsSync(sourcePath)) {
    console.warn(`  ! missing source: ${entry.source} (skipping ${entry.id})`);
    return null;
  }

  let touched = 0;
  for (const w of WIDTHS) {
    for (const fmt of FORMATS) {
      const outPath = join(OUT_DIR, `${entry.id}-${w}.${fmt}`);
      if (!(await needsRebuild(sourcePath, outPath))) continue;
      const pipe = sharp(sourcePath).resize({ width: w, withoutEnlargement: true });
      switch (fmt) {
        case 'avif':
          await pipe.avif({ quality: QUALITY.avif, effort: 4 }).toFile(outPath);
          break;
        case 'webp':
          await pipe.webp({ quality: QUALITY.webp, effort: 4 }).toFile(outPath);
          break;
        case 'jpg':
          await pipe.jpeg({ quality: QUALITY.jpg, mozjpeg: true }).toFile(outPath);
          break;
      }
      touched++;
    }
  }

  // 32px LQIP — base64 JPEG, blurred, very small.
  const lqipBuf = await sharp(sourcePath)
    .resize({ width: 32 })
    .blur(0.6)
    .jpeg({ quality: 40 })
    .toBuffer();
  const lqip = `data:image/jpeg;base64,${lqipBuf.toString('base64')}`;

  return { id: entry.id, lqip, touched };
}

async function main() {
  console.log(`[build-images] source: ${SOURCE_DIR}`);
  console.log(`[build-images] out:    ${OUT_DIR}`);

  // Vercel/CI: source originals aren't checked in, so the source dir is missing.
  // The committed public/img/ already contains the pre-built variants — skip cleanly.
  if (!existsSync(SOURCE_DIR)) {
    console.log('[build-images] source dir not present — using pre-built variants from public/img/. Skipping image generation.');
    return;
  }

  await mkdir(OUT_DIR, { recursive: true });

  const manifest = await loadManifest();
  console.log(`[build-images] ${manifest.length} entries`);

  const results = [];
  for (const entry of manifest) {
    const result = await processOne(entry);
    if (result) {
      results.push(result);
      console.log(`  ✓ ${entry.id} (+${result.touched} variants)`);
    }
  }

  const lqips = results.reduce((acc, r) => {
    acc[r.id] = r.lqip;
    return acc;
  }, /** @type {Record<string,string>} */ ({}));

  // Only rewrite the generated TS file when we actually produced LQIPs.
  // Otherwise the existing committed file is the source of truth.
  if (Object.keys(lqips).length > 0) {
    const generated = `/* AUTO-GENERATED by scripts/build-images.mjs — do not edit by hand. */
import type { PhotoId } from './photos';

export const lqips: Record<PhotoId, string> = ${JSON.stringify(lqips, null, 2)} as const;
`;
    await writeFile(GENERATED_PATH, generated);
    console.log(`[build-images] wrote ${GENERATED_PATH}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
